# Generated by Django 4.1.6 on 2023-04-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jralumniarchive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='addr1',
            field=models.CharField(help_text='Enter Addr Line 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='addr2',
            field=models.CharField(help_text='Enter Addr Line 2', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(help_text='Enter Addr City', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(help_text='Enter First Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(help_text='Enter Last Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='nickname',
            field=models.CharField(help_text='Enter NickName', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone1',
            field=models.CharField(help_text='Enter Phone', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(help_text='Enter Addr State', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip',
            field=models.CharField(help_text='Enter Addr Zip', max_length=10),
        ),
    ]
