# Generated by Django 4.1.6 on 2023-04-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jralumniarchive', '0002_alter_student_addr1_alter_student_addr2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyName', models.CharField(help_text='Enter Family Name', max_length=200)),
                ('student', models.ManyToManyField(help_text='Select a student for this family', to='jralumniarchive.student')),
            ],
        ),
    ]
